// Cloning Schema
CREATE SCHEMA OUR_FIRST_DB.COPIED_SCHEMA_CLONE
CLONE OUR_FIRST_DB.PUBLIC;

SELECT * FROM OUR_FIRST_DB.COPIED_SCHEMA_CLONE.ORDERS


// Cloning table
CREATE TABLE OUR_FIRST_DB.COPIED_SCHEMA_CLONE.ORDERS_CLONE
CLONE OUR_FIRST_DB.PUBLIC.ORDERS;

select * from OUR_FIRST_DB.COPIED_SCHEMA_CLONE.ORDERS_CLONE;

select count(1) from OUR_FIRST_DB.PUBLIC.ORDERS;

// Cloning Database
CREATE DATABASE OUR_FIRST_DB_CLONECOPY
CLONE OUR_FIRST_DB;

DROP DATABASE OUR_FIRST_DB_COPY
DROP SCHEMA OUR_FIRST_DB.EXTERNAL_STAGES_COPIED
DROP SCHEMA OUR_FIRST_DB.COPIED_SCHEMA
